### PR TITLE
closes #533

### LINKED ISSUE #533: [BUG] add support for new leagues
**Describe the bug**

**To Reproduce**

**Screenshots**

**Platform information:**
 - OS: [Windows / macOS / Linux]
 - Version (including build number)

**Additional context**

### PR DESCRIPTION
**Pull request by akasolace**
1. changes proposed in this pull request:
 
   - fixes issue #__  
   
   - if not fixing an existing issue, comments explaining the purpose of the PR should be provided)
 
 
2. changelog and release_notes ...

 - [ ] have been updated
 - [ ] do not require update

3. [Optional] suggested person to review this PR @___

### CODE REVIEW

File: src/main/java/core/model/WorldDetailsManager.java [hunk 1]
```diff
@@ -7,10 +7,10 @@
...
 
 	private static WorldDetailsManager WMANAGER = null;
-	private WorldDetailLeague[] leagues;
-	private HashMap<Integer, WorldDetailLeague> countryMap = new HashMap<Integer, WorldDetailLeague>();
-	private HashMap<Integer, WorldDetailLeague> leagueMap = new HashMap<Integer, WorldDetailLeague>();
-	private int totalUsers;
+	private static WorldDetailLeague[] leagues;
+	private static HashMap<Integer, WorldDetailLeague> countryMap = new HashMap<Integer, WorldDetailLeague>();
+	private static HashMap<Integer, WorldDetailLeague> leagueMap = new HashMap<Integer, WorldDetailLeague>();
+	private static int totalUsers;
```
Comment (tychobrailleur) [inline src/main/java/core/model/WorldDetailsManager.java:13]: Any reason for making all these `static`?  `WorldDetailsManager` seems to be a singleton, so `WorldDetailsManager.instance()` should do, and you can then call `getWorldDetailLeagueByCountryId` on it.

Comment (akasolace) [reply src/main/java/core/model/WorldDetailsManager.java:13]: no I guess we can go for your approach ... for my info what are the advantages of not making it static ?  I thought it would be cleaner this way ...

Comment (tychobrailleur) [reply src/main/java/core/model/WorldDetailsManager.java:13]: I usually dislike static because they are “viral” (makes other members static in the same class), and it makes it hard to unit tests, but here this is more for consistency: “state” classes like `HOVerwaltung`, `HOLogger`, `HOParameter`, `DBManager`, `User`, etc. etc. are all singletons, so this one would be the odd one out.

Comment (akasolace) [reply src/main/java/core/model/WorldDetailsManager.java:13]: Ok I am convinced ... I will do that then :-)

**Comment by akasolace** [comment]
I will merge it and do the changes you requested in another commit because I have too many conflicts to manage ...
