### PR TITLE
handover db location from script to HO.

### LINKED ISSUE #566: [BUG] repair artefacts build process following transition to install4j
**Describe the bug**

**To Reproduce**

**Screenshots**

**Platform information:**
 - OS: [Windows / macOS / Linux]
 - Version (including build number)

**Additional context**

### PR DESCRIPTION
**Pull request by akasolace**
1. changes proposed in this pull request:
 
   - closes #566 , #564, #548, #202 and  #372

   - information about portable vs installed App is passed by launcher

   - db location (and logs output) are now managed in HO based on platform and install type:
      - portable: same directory
      - windows: appdata 
      - linux  ~.ho 
      - maxOS Application Folder

   - Offers artefacts with bundled JREs

  Awaiting feedack before merging

### CODE REVIEW

File: src/main/java/core/HO.java [hunk 1]
```diff
@@ -20,34 +20,24 @@
...
+	}
 
-	/**
-	 * A RELEASE is when a build artifact gets delivered to users. Note that
-	 * even a DEVELOPMENT version can be a RELEASE ("Beta"). So when a version
-	 * is build (no matter if DEVELOPMENT or not), this flag should be set to
-	 * true. The main purpose for the flag is to disable code (unfinished new
-	 * features, debug code) which should not be seen in a release.
-	 */
+	private static boolean portable_version; // Used to determine along the os the location of te
```
Comment (tychobrailleur) [inline src/main/java/core/HO.java]: location of `te`?

File: src/main/java/core/db/User.java [hunk 2]
```diff
@@ -1,138 +1,146 @@
...
-				load();
+	public static String getDbParentFolder() {return dbParentFolder;}
+
+	private static void setDBParentFolder(){
+		if (! HO.isPortableVersion())
+		{
+			if (HO.getPlatform() == OSUtils.OS.LINUX) {
+				dbParentFolder = System.getProperty("user.home") + "/.ho";}
+			else if (HO.getPlatform() == OSUtils.OS.MAC) {
+				dbParentFolder =  System.getProperty("user.home") + "/Library/ApplicationSupport/HO";}
```
Comment (tychobrailleur) [inline src/main/java/core/db/User.java:63]: There should be a space between `Application` and `Support`.

Comment (akasolace) [reply src/main/java/core/db/User.java:63]: I think it was correct before so I don't know how I end up changing this one ...

File: src/main/java/core/HO.java (hunk 1 above)
Comment (akasolace) [reply src/main/java/core/HO.java]: I fixed this in last commit

File: src/main/java/core/db/User.java (hunk 2 above)
Comment (akasolace) [reply src/main/java/core/db/User.java:63]: > Apologies, I had just started the review when you merged.

No worry, I merged the PR because it started to be big and rebasing to master made the PR really messy. We might still have some issue but I think we are not far to have something solid

Comment (akasolace) [reply src/main/java/core/db/User.java:63]: done in 9c8ddeeab3cce923541ef88f0397bae914caa0cc

**Comment by pierpaolocira** [comment]
@akasolace I would like just to comment this description, that I could read only now.
I could say nothing (because this is already a PL and I know this is late), but I would prefer mentioning it now instead, at least you know.
As we have already mentioned several times, saving settings in "maxOS Application Folder" is not a good idea on MacOS.
They should be saved in the "Application Support" folder... as all other applicaitons do. In this way you're probably linking the DB with the specific installation and version.
Furthermore not only DB folder, but also other folders are now saved in the main folder of the user... please check that also those are saved in the same folder of the DB...
