### PR TITLE
closes #505

### LINKED ISSUE #505: [eBUG] Module Evil Card is broken
@wsbrenk @tychobrailleur   Should we repair it or is it also a candidate for removal?  I personally never used it ...

### PR DESCRIPTION
**Pull request by akasolace**
Remove evil card module

I was not sure about the icons so I did not touched them

### CODE REVIEW

File: src/main/java/core/module/ModuleManager.java [hunk 1]
```diff
@@ -56,9 +55,7 @@ private void initMap(Map<Integer, IModule> map) {
 		map.put(Integer.valueOf(IModule.TSFORECAST), new TSForecastModule());
 		map.put(Integer.valueOf(IModule.SPECIALEVENTS), new SpecialEventsModule());
 		map.put(Integer.valueOf(IModule.TEAM_OF_THE_WEEK), new TeamOfTheWeekModule());
-		map.put(Integer.valueOf(IModule.EVIL_CARD), new EvilCardModule());
```
Comment (tychobrailleur) [inline src/main/java/core/module/ModuleManager.java:59]: Do we want to remove `EVIL_CARD` from `IModule` too?

Comment (akasolace) [reply src/main/java/core/module/ModuleManager.java:59]: yes you are right
